version: '3'

services:
  adminer:
    container_name: si8_adminer
    image: adminer:latest
    restart: on-failure
    ports:
      - 8080:8080
    networks:
      - default
      - postgres

  db:
    container_name: si8_db
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: si8
    ports:
      - 5432:5432
    networks:
      - default
      - postgres

networks:
  postgres: {}
