version: '3'

services:
  db:
    container_name: si8_db
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: si8
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - default
      - postgres

  api:
    container_name: si8_api
    restart: on-failure
    image: node:8
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    networks:
      - default
      - postgres
      - web
    command: ['node', '/api/src/build/server.js']
    labels:
      - 'traefik.docker.network=web'
      - 'traefik.enable=true'
      - 'traefik.domain=api.winnersnevers.top'
      - 'traefik.basic.frontend.rule=Host:api.winnersnevers.top'
      - 'traefik.basic.port=3000'
      - 'traefik.basic.protocol=http'
      - 'traefik.frontend.headers.SSLRedirect=true'
      - 'traefik.frontend.headers.STSSeconds=315360000'
      - 'traefik.frontend.headers.browserXSSFilter=true'
      - 'traefik.frontend.headers.contentTypeNosniff=true'
      - 'traefik.frontend.headers.forceSTSHeader=true'
      - 'traefik.frontend.headers.referrerPolicy=no-referrer'
      - 'traefik.frontend.headers.frameDeny=true'

volumes:
  db_data:

networks:
  web:
    external: true
  postgres: {}
